### ISSUE TITLE
Battery charging and discharging

### ISSUE THREAD

**Issue by Woempia** [faanskit/ha-esolar#3]
It would be great to be able to charge and discharge the battery and control it through home assistant (with an automation for example). Is this something you would consider looking into?

**Comment by faanskit** [comment]
For sure it can be considered, but two constraints:

1. I don't own a battery system
2. I am limited to what can be done in the SAJ portal

If you can confirm that charge/discharge can be controlled in the SAJ portal we can start looking into it. 

It would entail on your side:
A. Confirming the above
B. Capturing portal communication when performing actions (Chrome dev mode) 
C. Doing guided trials (I send you files, you need python) 
D. Worst case: sharing your username/password


So, please send some screenshot how to charge / discharge in the portal.

Br, Marcus

**Comment by Woempia** [comment]
It appears that a new app had been launched: Esaj Home

-There is an option 'outage guard' in the app, which I believe allows you to force charge the battery 
- you can access the battery inverter through this app as well, where you can set operating mode and charge and discharge time. I am not sure we could access this through HA

It may be more time efficiënt to progress with the new esaj home app? Would you be open to look at this as well ? 

Also see below email from SAJ service team:

"Hello:

Please download esaj home app. It's the newest app for end user and available in app store now. 

Click the botton right logo>click remote configuration>click bluetooth to connect your inverter. You will see a working mode setting there, choose time of use mode and set specific charge/discharge period. "

![Screenshot_20221223_125058_eSAJ Home](https://user-images.githubusercontent.com/99049720/209332531-1704525a-ec7a-4bb4-beb6-807d8a6c853d.jpg)

**Comment by faanskit** [comment]
Hi,

I see one major problem, one potential problem and one annoyance.

1. MAJOR PROBLEM
The comment from SAJ mentions Bluetooth. This invalidates the possibility to use the cloud services. I will not have the possibility/competence to create such a solution.

2. POTENTIAL PROBLEM
The SAJ eSolar APP uses a secret encryption for most of the GET requests. Unless Saj share the secret (seed), or someone reverse engineer the app and find the secret key (seed) we have a problem.
I've asked Saj for the secret key, without success.

3. ANNOYANCE
The reverse engineer the app is quite combersome compared to the portal. One need to use a Man-in-the-middle attack to succeed. Newer Androiod phones and IPhones does not a allow to use own keys to enable tools like MITM Proxy.
So, unless the new app also work on an old iphone/ipad, this will be extremely hard.

/Marcus

**Comment by Woempia** [comment]
1) within the app there are 3 ways to connect to the inverter (bluetooth, wifi and cloud). SAJ only mentions bluetooth, for the other methods i get the message when I try it that i do not have the right permissions. I am already checking with SAJ to see which type of account is needed to get the permissions 

![Screenshot_20221223_175415_eSAJ Home](https://user-images.githubusercontent.com/99049720/209372832-350310ec-b061-4488-bf20-8b2a30bd56ee.jpg)

2) let me know if there is anything I can do. Not sure why you are referencing the esolar app here vs the esaj home app

3) I did not register you were taking the data from the portal vs from the app. The portal does not seem to have the option of 'outage guard'

I'll update on 1 when I hear back from SAJ, I'll also ask about 3

**Comment by faanskit** [comment]
Wrt. 2, see my findings on esolar app parameter encryption here:
https://github.com/djansen1987/SAJeSolar/issues/27

If the new app use same encryption we're stuck.

The current integration use the web portal api.

**Comment by robshot** [comment]
Just some FYI information, if somewhere in the app (only tested on the old app) they ask for a password, try this: saj_admin.
There is also an app for installers, it's called eSolar O&M, if you click on local connection the ask for a password, it's the saj_admin. you have little bit more permissions.
Have found this on a video on youtube with 10 views :p
